export const BooleanAlgebraRelations = {
    Precedes: 'Precedes',
    Meets: 'Meets',
    Overlaps: 'Overlaps',
    Finished_by: 'Finished by',
    Contains: 'Contains',
    Start: 'Start',
    Equal: 'Equal',
    Started_by: 'Started by',
    During: 'During',
    Finishes: 'Finishes',
    Overlapped_by: 'Overlapped by',
    Met_by: 'Met by',
    Preceded_by: 'Preceded by',
};
