import { createTheme } from '@fluentui/style-utilities';

export const lightTheme = createTheme({
    palette: {
        themePrimary: '#006e3f',
        themeLighterAlt: '#eff9f5',
        themeLighter: '#c3e8d8',
        themeLight: '#94d3b8',
        themeTertiary: '#43a87c',
        themeSecondary: '#0f7f4f',
        themeDarkAlt: '#006338',
        themeDark: '#00532f',
        themeDarker: '#003d23',
        neutralLighterAlt: '#faf9f8',
        neutralLighter: '#f3f2f1',
        neutralLight: '#edebe9',
        neutralQuaternaryAlt: '#e1dfdd',
        neutralQuaternary: '#d0d0d0',
        neutralTertiaryAlt: '#c8c6c4',
        neutralTertiary: '#a19f9d',
        neutralSecondary: '#605e5c',
        neutralPrimaryAlt: '#3b3a39',
        neutralPrimary: '#323130',
        neutralDark: '#201f1e',
        black: '#000000',
        white: '#ffffff',
    },
});

export const darkTheme = createTheme({
    palette: {
        themePrimary: '#00ff91',
        themeLighterAlt: '#000a06',
        themeLighter: '#002917',
        themeLight: '#004d2b',
        themeTertiary: '#009957',
        themeSecondary: '#00e07f',
        themeDarkAlt: '#19ff9c',
        themeDark: '#3dffab',
        themeDarker: '#70ffc1',
        neutralLighterAlt: '#323232',
        neutralLighter: '#313131',
        neutralLight: '#2f2f2f',
        neutralQuaternaryAlt: '#2c2c2c',
        neutralQuaternary: '#2a2a2a',
        neutralTertiaryAlt: '#282828',
        neutralTertiary: '#c8c8c8',
        neutralSecondary: '#d0d0d0',
        neutralPrimaryAlt: '#dadada',
        neutralPrimary: '#ffffff',
        neutralDark: '#f4f4f4',
        black: '#f8f8f8',
        white: '#333333',
    },
});
