import { createTheme } from '@fluentui/style-utilities';

export const lightTheme = createTheme({
    palette: {
        themePrimary: '#0078d4',
        themeLighterAlt: '#eff6fc',
        themeLighter: '#deecf9',
        themeLight: '#c7e0f4',
        themeTertiary: '#71afe5',
        themeSecondary: '#2b88d8',
        themeDarkAlt: '#106ebe',
        themeDark: '#005a9e',
        themeDarker: '#004578',
        neutralLighterAlt: '#faf9f8',
        neutralLighter: '#f3f2f1',
        neutralLight: '#edebe9',
        neutralQuaternaryAlt: '#e1dfdd',
        neutralQuaternary: '#d0d0d0',
        neutralTertiaryAlt: '#c8c6c4',
        neutralTertiary: '#a19f9d',
        neutralSecondary: '#605e5c',
        neutralPrimaryAlt: '#3b3a39',
        neutralPrimary: '#323130',
        neutralDark: '#201f1e',
        black: '#000000',
        white: '#ffffff',
    },
});

export const darkTheme = createTheme({
    palette: {
        themePrimary: '#69beff',
        themeLighterAlt: '#04080a',
        themeLighter: '#111e29',
        themeLight: '#1f394d',
        themeTertiary: '#3f7299',
        themeSecondary: '#5ca7e0',
        themeDarkAlt: '#78c4ff',
        themeDark: '#8dcdff',
        themeDarker: '#abdaff',
        neutralLighterAlt: '#3c3b39',
        neutralLighter: '#444241',
        neutralLight: '#514f4e',
        neutralQuaternaryAlt: '#595756',
        neutralQuaternary: '#5f5e5c',
        neutralTertiaryAlt: '#7a7977',
        neutralTertiary: '#c8c8c8',
        neutralSecondary: '#d0d0d0',
        neutralPrimaryAlt: '#dadada',
        neutralPrimary: '#ffffff',
        neutralDark: '#f4f4f4',
        black: '#f8f8f8',
        white: '#323130',
    },
});
